services:
  - type: web
    name: bank-reports
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bank_reports_complete.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bank_reports.settings
      - key: PYTHON_VERSION
        value: 3.11
